version: 2
updates:
  - package-ecosystem: npm
    directory: /clients/node
    allow:
      - dependency-type: development
    ignore:
      - dependency-name: "@types/node"
        versions:
          - ">=23"
    schedule:
      interval: weekly
    groups:
      development:
        dependency-type: "development"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
