version: "3"
services:

  localstack:
    image: localstack/localstack:3
    networks:
      - hmpps
    container_name: localstack
    ports:
      - "4566:4566"
      - "8999:8080"
    environment:
      - DEBUG=${DEBUG- }
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

  non-associations-db:
    image: postgres
    networks:
      - hmpps
    container_name: non-associations-db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=non_associations
      - POSTGRES_USER=non_associations
      - POSTGRES_DB=non_associations

networks:
  hmpps:
