version: "3"
services:

  localstack:
    image: localstack/localstack:2.0
    networks:
      - hmpps
    container_name: localstack
    ports:
      - "4566:4566"
      - "8999:8080"
    environment:
      - DEBUG=${DEBUG- }
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

  hmpps-auth:
    image: quay.io/hmpps/hmpps-auth:latest
    networks:
      - hmpps
    container_name: hmpps-auth
    ports:
      - "9090:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/auth/health"]
    environment:
      - SPRING_PROFILES_ACTIVE=dev,nomis
      - APPLICATION_AUTHENTICATION_UI_ALLOWLIST=0.0.0.0/0
      - NOMIS_ENDPOINT_URL=http://nomis-user-roles-api:8080

  nomis-user-roles-api:
    image: quay.io/hmpps/nomis-user-roles-api:latest
    networks:
      - hmpps
    container_name: nomis-user-roles-api
    depends_on:
      - hmpps-auth
    ports:
      - "8084:8080"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/health" ]
    environment:
      - SERVER_PORT=8080
      - SPRING_PROFILES_ACTIVE=dev
      - API_BASE_URL_OAUTH=http://hmpps-auth:8080/auth

  prison-api:
    image: quay.io/hmpps/prison-api:latest
    networks:
      - hmpps
    container_name: prison-api
    depends_on:
      - hmpps-auth
    ports:
      - "8082:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/auth/health"]
    environment:
      - SPRING_PROFILES_ACTIVE=nomis-hsqldb

  non-associations-db:
    image: postgres
    networks:
      - hmpps
    container_name: non-associations-db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=non_associations
      - POSTGRES_USER=non_associations
      - POSTGRES_DB=non_associations

networks:
  hmpps:
