hmpps.sqs:
  reactiveApi: true
  provider: localstack
  queues:
    audit:
      queueName: ${random.uuid}
    nonassociations:
      queueName: non-associations-event-queue
      dlqName: non-associations-event-dlq
      subscribeTopicId: domainevents
      subscribeFilter: '{"eventType":[ "prison-offender-events.prisoner.merged" ] }'
  topics:
    domainevents:
      arn: arn:aws:sns:eu-west-2:000000000000:11111111-2222-3333-4444-555555555555
