server:
  shutdown: immediate

api:
  base:
    url:
      oauth: http://localhost:9090/auth
      prison: http://localhost:8082
      offender-search: http://localhost:8083

management.endpoint:
  health.cache.time-to-live: 0
  info.cache.time-to-live: 0

spring:
  devtools:
    add-properties: true

  flyway:
    url: jdbc:postgresql://localhost:5432/non_associations?sslmode=prefer
    user: non_associations
    password: non_associations

#  r2dbc:
#    url: r2dbc:postgresql://localhost:5432/non_associations?sslmode=prefer
#    username: non_associations
#    password: non_associations
#    properties:
#      sslMode: DISABLE
#      sslRootCert:

  feature-toggles:
    afine: true
