generic-service:
  replicaCount: 2

  scheduledDowntime:
    enabled: true

  ingress:
    host: non-associations-api-preprod.hmpps.service.justice.gov.uk

  env:
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.dev.json
    API_BASE_URL_OAUTH: https://sign-in-preprod.hmpps.service.justice.gov.uk/auth
    API_BASE_URL_OFFENDER_SEARCH: https://prisoner-search-preprod.prison.service.justice.gov.uk

generic-prometheus-alerts:
  alertSeverity: digital-prison-service-dev
  businessHoursOnly: true
  rdsAlertsDatabases:
    cloud-platform-b6126468990788eb: non-associations-api
  sqsAlertsQueueNames:
    - hmpps-non-associations-preprod-prisoner-event-queue
    - hmpps-non-associations-preprod-prisoner-event-dlq
