generic-service:
  replicaCount: 2

  scheduledDowntime:
    enabled: true

  ingress:
    host: non-associations-api-dev.hmpps.service.justice.gov.uk

  allowlist: null

  env:
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.dev.json
    API_BASE_URL_OAUTH: https://sign-in-dev.hmpps.service.justice.gov.uk/auth
    API_BASE_URL_OFFENDER_SEARCH: https://prisoner-search-dev.prison.service.justice.gov.uk

generic-prometheus-alerts:
  alertSeverity: digital-prison-service-dev
  businessHoursOnly: true
  rdsAlertsDatabases:
    cloud-platform-7534158a562cce9e: non-associations-api
  sqsAlertsQueueNames:
    - hmpps-non-associations-development-prisoner-event-queue
    - hmpps-non-associations-development-prisoner-event-dlq
