generic-service:
  ingress:
    host: non-associations-api.hmpps.service.justice.gov.uk

  env:
    API_BASE_URL_OAUTH: https://sign-in.hmpps.service.justice.gov.uk/auth
    API_BASE_URL_PRISONER_SEARCH: https://prisoner-search.prison.service.justice.gov.uk

  postgresDatabaseRestore:
    enabled: true
    namespace_secrets:
      dps-rds-instance-output:
        DB_NAME: "database_name"
        DB_USER: "database_username"
        DB_PASS: "database_password"
        DB_HOST: "rds_instance_address"
      dps-rds-instance-output-preprod:
        DB_NAME_PREPROD: "database_name"
        DB_USER_PREPROD: "database_username"
        DB_PASS_PREPROD: "database_password"
        DB_HOST_PREPROD: "rds_instance_address"

generic-prometheus-alerts:
  alertSeverity: hmpps-non-associations-prod
  rdsAlertsDatabases:
    cloud-platform-994c511ab5935ecc: non-associations-api
  sqsAlertsQueueNames:
    - hmpps-non-associations-production-prisoner-event-queue
    - hmpps-non-associations-production-prisoner-event-dlq
