---
# Per environment values which override defaults in hmpps-non-associations-api/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: non-associations-api-preprod.hmpps.service.justice.gov.uk

  env:
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.dev.json
    API_BASE_URL_OAUTH: https://sign-in-preprod.hmpps.service.justice.gov.uk/auth
    API_BASE_URL_PRISON: https://api-preprod.prison.service.justice.gov.uk
    API_BASE_URL_OFFENDER_SEARCH: https://prisoner-offender-search-preprod.prison.service.justice.gov.uk
    FEATURE_LEGACY_ENDPOINT_NOMIS_SOURCE_OF_TRUTH: true

  modsecurity_enabled: true
  modsecurity_snippet: |
    SecRuleEngine DetectionOnly
    SecRuleUpdateActionById 949110 "t:none,deny,status:406,logdata:%{SERVER_NAME}"
    SecRuleUpdateActionById 959100 "t:none,deny,status:406,logdata:%{SERVER_NAME}"
    SecAction "id:900000,phase:1,nolog,pass,t:none,setvar:tx.paranoia_level=2"


# CloudPlatform AlertManager receiver to route prometheus alerts to slack
# See https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#creating-your-own-custom-alerts
generic-prometheus-alerts:
  alertSeverity: digital-prison-service-dev
