name: Test REST client
on:
  workflow_call:
    inputs:
      node-version:
        description: Node version
        required: true
        type: number
jobs:
  test:
    name: Test REST client on node ${{ inputs.node-version }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout sources
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7

      - name: Setup node ${{ inputs.node-version }}
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version: ${{ inputs.node-version }}

      - name: Install npm dependencies
        shell: bash
        run: |
          cd clients/node
          npm install --no-audit

      - name: Build library
        shell: bash
        run: |
          cd clients/node
          npm run build

      - name: Run linter
        shell: bash
        run: |
          cd clients/node
          npm run lint

      - name: Run tests
        shell: bash
        run: |
          cd clients/node
          npm test

      - name: Upload test results
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        with:
          name: npm-test-results-${{ inputs.node-version }}
          path: |
            ./clients/node/test_results

      - name: Publish test report
        if: ${{ !cancelled() }}
        uses: dorny/test-reporter@a43b3a5f7366b97d083190328d2c652e1a8b6aa2 # v3
        with:
          name: Test report for node ${{ inputs.node-version }}
          artifact: npm-test-results-${{ inputs.node-version }}
          path: junit.xml
          reporter: jest-junit
          fail-on-empty: false
          fail-on-error: false
